"""PlatformIO pre-script: stamp the image with the commit it was built from.

Writes include/build_id.h (gitignored) with NODE_BUILD_ID = "<sha7>[-dirty] <UTC time>", the
string the node reports in /ota/status and the console. It is the only trustworthy way to tell
which image a node runs after an OTA: "the upload was accepted" proves nothing about the flash.
Only Ota.cpp includes the header, so a new stamp recompiles one file.
"""
import datetime
import os
import subprocess

Import("env")  # noqa: F821 (PlatformIO injects it)

root = env.subst("$PROJECT_DIR")  # noqa: F821


def git(*args):
    try:
        return subprocess.check_output(["git", *args], cwd=root, stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        return ""


sha = git("rev-parse", "--short=7", "HEAD") or "nogit"
dirty = "-dirty" if git("status", "--porcelain", "--untracked-files=no") else ""
stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M")
build_id = "%s%s %s" % (sha, dirty, stamp)

path = os.path.join(root, "include", "build_id.h")
content = "// generated by tools/build_id.py at build time, not tracked\n#pragma once\n#define NODE_BUILD_ID \"%s\"\n" % build_id
with open(path, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print("build id:", build_id)
