"""PlatformIO pre-script: put the LAN API key into the build without putting it in the repo.

The HTTP API (OTA, docs/ota.md; settings, docs/config.md) authenticates with a pre-shared key.
It lives next to the boot signing keys, in NODE_KEYS_DIR (default ~/.rp2350-keys) as
api_psk.hex, and this script writes it into include/node_secrets.h (gitignored) for the build.
The first build on a machine without one generates a random key, so every builder has their own.
NODE_API_PSK (64 hex chars) in the environment overrides the file.

The host tools (tools/ota_upload.py, tools/node_config.py) read the same file. Lose it and the
boards built with it only take a new image by USB (docs/ota.md); back it up with the boot keys.
"""
import os
import re
import secrets

Import("env")  # noqa: F821 (PlatformIO injects it)

root = env.subst("$PROJECT_DIR")  # noqa: F821
keys_dir = os.environ.get("NODE_KEYS_DIR") or os.path.join(os.path.expanduser("~"), ".rp2350-keys")
key_path = os.path.join(keys_dir, "api_psk.hex")

psk = os.environ.get("NODE_API_PSK", "").strip()
source = "NODE_API_PSK"
if not psk:
    if os.path.exists(key_path):
        with open(key_path, encoding="ascii") as f:
            psk = f.read().strip()
        source = key_path
    else:
        psk = secrets.token_hex(32)
        os.makedirs(keys_dir, exist_ok=True)
        with open(key_path, "w", encoding="ascii", newline="\n") as f:
            f.write(psk + "\n")
        os.chmod(key_path, 0o600)
        source = key_path + " (new)"
        print("\n" + "!" * 78 + "\n!! Generated a new LAN API key in %s.\n"
              "!! Back it up with the boot keys: an image built with it only takes OTA uploads\n"
              "!! from a host that has it.\n" % key_path + "!" * 78 + "\n")
if not re.fullmatch(r"[0-9a-fA-F]{64}", psk):
    raise SystemExit("node_secrets: the API key from %s is not 64 hex chars" % source)

path = os.path.join(root, "include", "node_secrets.h")
content = ("// generated by tools/node_secrets.py at build time, not tracked\n#pragma once\n"
           "#define NODE_API_PSK_HEX \"%s\"\n" % psk.lower())
old = None
if os.path.exists(path):
    with open(path, encoding="utf-8") as f:
        old = f.read()
if old != content:
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
print("api key: from", source)
